lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Mike Gifford
logo: /media/Open_UK_SOOC250460.jpg
description: Personal landing page
show_downloads: false
theme: jekyll-theme-minimal
include: [".well-known"]

